version: "3"
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_NUM_PARTITIONS=4
    depends_on:
      - zookeeper
  database:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=messages
  saga1:
    image: kafkasaga
    ports:
      - '8181:8181'
    environment:
      - INSTANCE_ID=1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/messages
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  saga2:
    image: kafkasaga
    ports:
      - '8182:8181'
    environment:
      - INSTANCE_ID=2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/messages
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  saga3:
    image: kafkasaga
    ports:
      - '8183:8181'
    environment:
      - INSTANCE_ID=3
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/messages
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
  saga4:
    image: kafkasaga
    ports:
      - '8184:8181'
    environment:
      - INSTANCE_ID=4
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/messages
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
volumes:
  database-data: